"""
工具模块
"""
from .logging_setup import setup_logging
from .qlib_utils import (
    convert_qlib_date,
    convert_to_qlib_date,
    parse_instruments_file,
    parse_calendar_file,
    get_qlib_data_dir,
    get_qlib_freq_mapping,
    get_qlib_fields_mapping,
    convert_to_qlib_fields,
    convert_from_qlib_fields,
    validate_qlib_data,
    align_with_qlib_calendar,
    calculate_missing_dates,
    convert_qlib_bin_to_df,
    compare_with_qlib
)
from .duckdb_utils import (
    optimize_duckdb_connection,
    create_duckdb_index,
    analyze_table,
    export_table_to_parquet,
    import_from_parquet,
    execute_query_with_stats,
    vacuum_database,
    get_database_size,
    create_materialized_view,
    bulk_insert_dataframe
)
from .performance import (
    PerformanceMonitor,
    time_it,
    timer_context,
    get_system_stats,
    QueryBenchmark,
    profile_memory,
    analyze_query_performance,
    generate_performance_report
)
from .validation import (
    validate_price_data,
    validate_calendar,
    validate_instrument_df,
    get_table_stats
)

__all__ = [
    'setup_logging',
    'convert_qlib_date',
    'convert_to_qlib_date',
    'parse_instruments_file',
    'parse_calendar_file',
    'get_qlib_data_dir',
    'get_qlib_freq_mapping',
    'get_qlib_fields_mapping',
    'convert_to_qlib_fields',
    'convert_from_qlib_fields',
    'validate_qlib_data',
    'align_with_qlib_calendar',
    'calculate_missing_dates',
    'convert_qlib_bin_to_df',
    'compare_with_qlib',
    'optimize_duckdb_connection',
    'create_duckdb_index',
    'analyze_table',
    'export_table_to_parquet',
    'import_from_parquet',
    'execute_query_with_stats',
    'vacuum_database',
    'get_database_size',
    'create_materialized_view',
    'bulk_insert_dataframe',
    'PerformanceMonitor',
    'time_it',
    'timer_context',
    'get_system_stats',
    'QueryBenchmark',
    'profile_memory',
    'analyze_query_performance',
    'generate_performance_report',
    'validate_price_data',
    'validate_calendar',
    'validate_instrument_df',
    'get_table_stats'
]